version: '2'
services:
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - nginx
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEFAULT_SSL_CERT=-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA0SFn9EgsYMVnkC0PT2CkJxkGSEfQttWLJ2qaTEh19OVay0Rh\nBF5GcOhJSzAXjwl6ARxJHrIIewxP4P43P8yclFMeM6GdKPRW3xoUJYnxbE5XZ+Ed\ntctpp7ckt8qEsZZLT0LEgDeIrS3mVyVa145WSy/O8e3fhFmKjGrCXpTd05drsaUE\nwbmR7kfAWW+3K+8duVciBL4giu1N7w0/nYtPlhDA05w8+LIFuaYIFq/hG1l9CdwF\nWzpBsxsQMMBJz4OX/Goxqzjg2sGL1CGnNYt0lIbLrF2Ii2SNt9jaZo0rViqY6FyP\n+61oZxO/yxYogaFeFgcrraQTh4uRK9s3G+r05wIDAQABAoIBAGUTa0Xi2CgRYOOL\nE7o+sDgBXUr0AslLXo03dcnmv7QUYhSaQPW2hv8tFbeUT96fKut8e06tp3GpWrYY\nyCU6xHbf0VoNA4N2zMHZveEC0b+SAabAY/aokLEx0DpQVF/sjwuI7qY1sQZah9iY\nwlYqgkSmn7PIT16NVGxXcQf7lVcdGPpZtrJbLNB1NV0gRUpKsdGWTyyt6Oo7cnxp\nCEyDDjgkn9FsEU4n6/6nZCSWI4TiTjWbxzqENTl5e5LXJHe+jojLI2YbtaoUCBoF\nPVQfJKHfyI50JzGqs5J6mHo2GkY5k0Hhibzg2CajQN10fiZpwGoQWKe7RwdwNZqh\nByvgZvECgYEA+OhHTdDEm8eiKtAvt8xdy6WYe7oXUOqwkcxTmPtpAb5I1Zatb8dH\noj+RnOpsjI2c5407OPcqJTZd3LVm3R8MHT3pQy3HiHq9xaBhluiRoy0MROfUZr0K\njNGdEr7KELDJup+2Zj0opSbQWVEv63GWutyiRlFe6xR8bfHRzo5jcRkCgYEA1xb2\n81aMubt2R/g8cjcVqfF5xJVWY7Z56RTNvLvCaY4EW2aa3w15BBRSvcF9AuJPGnAT\npWiZ/mRj3pOx4WdS23e7Qiltue1yEafzofP9ARrCl0T4bNmDhv7uVnWPQv03N6js\nrJsfWTXPVFWRSGkhk3D+Im+kuPWbawFHfQ7QVf8CgYEA9ycV3lPFVfXFtgNgzn2U\nSSmWHo0qp8NSLoOYItjJbNy4T7W9Y7eaDqZWfVxdCrd3LIkVXDw40hiI3SYXDMvO\naJ7YJ0em0IMoOrtFC+bE7iVGAIm+Y4Gkny1obXubAzW4KaJ7KEvkNxEyYu31yjDQ\n/Z0lWPNlb8G4yCcNMLA8V8kCgYB4zjwrljv6AZFAgOsqV0gCqE71G89mt9GnGPko\n/OgHsy09TNbFWuLSaLvEOk2Fdihpt/NA3wxG9omlNJ0e9ZJzE7+IPI6VdAiyY/uR\nxeEfYrFSlvlU4aJfCwZAZ0zsmh4OVAGCPKoRyAhH3Lt5yRqDnl4OZ1hETiZZpmFJ\nmy1mbwKBgQCYGStsxfD6K460a623F3cBAKSwChgdhArmp60oukHNn25gkA2uWVqY\nRZ9+k5XWlkxsWzJ2xP7jdXTeltsKK7ZeThEe1HoZzYNPjBs3uvdz1s5lvvWT7ZfD\n25x/Vixg/JPS9oA5h73sN3iV/gaMe+xU2D4JcC7dK0HLF/pbkTaolA==\n-----END RSA PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIEbjCCA1agAwIBAgIJAMtTlxHGHsWZMA0GCSqGSIb3DQEBCwUAMIGAMQswCQYD\nVQQGEwJLRTEQMA4GA1UECBMHTmFpcm9iaTEQMA4GA1UEBxMHTmFpcm9iaTEXMBUG\nA1UEChMORGphbmdvVGVsZWdyYW0xNDAyBgNVBAMTK2xiLmRqYW5nb3RlbGVncmFt\nLjYyYmJhYjVkLnN2Yy5kb2NrZXJhcHAuaW8wHhcNMTYwMzI4MDU1MjA1WhcNMTcw\nMzI4MDU1MjA1WjCBgDELMAkGA1UEBhMCS0UxEDAOBgNVBAgTB05haXJvYmkxEDAO\nBgNVBAcTB05haXJvYmkxFzAVBgNVBAoTDkRqYW5nb1RlbGVncmFtMTQwMgYDVQQD\nEytsYi5kamFuZ290ZWxlZ3JhbS42MmJiYWI1ZC5zdmMuZG9ja2VyYXBwLmlvMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0SFn9EgsYMVnkC0PT2CkJxkG\nSEfQttWLJ2qaTEh19OVay0RhBF5GcOhJSzAXjwl6ARxJHrIIewxP4P43P8yclFMe\nM6GdKPRW3xoUJYnxbE5XZ+Edtctpp7ckt8qEsZZLT0LEgDeIrS3mVyVa145WSy/O\n8e3fhFmKjGrCXpTd05drsaUEwbmR7kfAWW+3K+8duVciBL4giu1N7w0/nYtPlhDA\n05w8+LIFuaYIFq/hG1l9CdwFWzpBsxsQMMBJz4OX/Goxqzjg2sGL1CGnNYt0lIbL\nrF2Ii2SNt9jaZo0rViqY6FyP+61oZxO/yxYogaFeFgcrraQTh4uRK9s3G+r05wID\nAQABo4HoMIHlMB0GA1UdDgQWBBQqxRK2+BQZyB0g+1d+nZC8XINDGjCBtQYDVR0j\nBIGtMIGqgBQqxRK2+BQZyB0g+1d+nZC8XINDGqGBhqSBgzCBgDELMAkGA1UEBhMC\nS0UxEDAOBgNVBAgTB05haXJvYmkxEDAOBgNVBAcTB05haXJvYmkxFzAVBgNVBAoT\nDkRqYW5nb1RlbGVncmFtMTQwMgYDVQQDEytsYi5kamFuZ290ZWxlZ3JhbS42MmJi\nYWI1ZC5zdmMuZG9ja2VyYXBwLmlvggkAy1OXEcYexZkwDAYDVR0TBAUwAwEB/zAN\nBgkqhkiG9w0BAQsFAAOCAQEAXgOucOrEGD3K5iRKIufIBA+j+KJoejpJqcjwTV0W\nr3/FPeIMLIlUL4qcgjWUzXYV80gdGXqvnkhA2/kTuII8GhtvjR7g/PPHGztni24b\nYOiDUpfb7LP+7BDskzo1XZknYntOZvu/hqVV0YYkoToYyElGRLw7/VY+s+Y8ma9j\nBBnEjRm80VKrqIWNUErLF46du066MJ5CF+32NPNV1oNYSb1Kl/YTQkY+fDWowKRE\nR9h3Ewp29LLVaqWZ/lfE33eScawkMoeqCsxmhn/ZT55bZMPyDT9EGxazgJL4o1Rg\nRSTRqGLpZwDBvrIG7zGlUXnQQhkKspdghup8+ami9bnUFg==\n-----END CERTIFICATE-----\n
    ports:
      - '8003:80'
      - '443:443'
      - '1936:1936'

  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=django_telegram
      - POSTGRES_PASSWORD=mysecretpassword

  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - '8080:80'
    links:
      - db
    environment:
      - 'VIRTUAL_HOST=http://*/*, https://*/*'
      - 'DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/django_telegram'
      - RAVEN_DNS=https://9f607d7813e54aa8a91295812b706c28:725accda92c447488383b51fcb97b8ac@app.getsentry.com/66589
      - TELEGRAM_TOKEN=179088213:AAHa4O5QUwsF91R60FnFHrFVTpA5eYUk0Tw

  nginx:
    build:
      context: .
      dockerfile: nginx_dockerfile
    volumes:
      - ./static:/usr/src/static/
    environment:
      - 'VIRTUAL_HOST=http://*/static/*, https://*/static/*'
      - VIRTUAL_HOST_WEIGHT=1

